# Generated by Django 4.0.2 on 2022-02-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='updated_on',
        ),
    ]
