name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup
      run:
        python manage.py makemigrations
        python manage.py sqlmigrate users 0001
        python manage.py migrate
        python manage.py makemigrations blog
        python manage.py sqlmigrate blog 0001
        python manage.py migrate
        
    - name: Make envfile
    - uses: actions/dotenv-action
      with:
        envkey_SECRET_KEY: 12345
        directory: /schirus/
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Tests
      run: actions
        python manage.py test
